[build]
  command = "npm run netlify-build"

  functions = "netlify/functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Handle Next.js image optimization requests
[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/images"
  status = 200
  force = true
  [redirects.query]
    url = ":url"
    w = ":width"
    q = ":quality"

# Add caching headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
